// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOkgvk-myJaAfYpmQ7iirIjhvqg6BVjA8',
    appId: '1:685788441650:web:31e9ae615300c77833a02b',
    messagingSenderId: '685788441650',
    projectId: 'edu-bridge-e58f4',
    authDomain: 'edu-bridge-e58f4.firebaseapp.com',
    storageBucket: 'edu-bridge-e58f4.appspot.com',
    measurementId: 'G-VWF815N35G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsX8AFAoylPTUdDkCiOJUzdVjpwPsWDDU',
    appId: '1:685788441650:android:1dda37ee9de6860933a02b',
    messagingSenderId: '685788441650',
    projectId: 'edu-bridge-e58f4',
    storageBucket: 'edu-bridge-e58f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKiIqwTlnUMzpS-g8uPcA5RSkJgSCinME',
    appId: '1:685788441650:ios:a5d7e3441473047033a02b',
    messagingSenderId: '685788441650',
    projectId: 'edu-bridge-e58f4',
    storageBucket: 'edu-bridge-e58f4.appspot.com',
    iosBundleId: 'com.example.eduBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKiIqwTlnUMzpS-g8uPcA5RSkJgSCinME',
    appId: '1:685788441650:ios:a5d7e3441473047033a02b',
    messagingSenderId: '685788441650',
    projectId: 'edu-bridge-e58f4',
    storageBucket: 'edu-bridge-e58f4.appspot.com',
    iosBundleId: 'com.example.eduBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOkgvk-myJaAfYpmQ7iirIjhvqg6BVjA8',
    appId: '1:685788441650:web:ffdab2006a7822e733a02b',
    messagingSenderId: '685788441650',
    projectId: 'edu-bridge-e58f4',
    authDomain: 'edu-bridge-e58f4.firebaseapp.com',
    storageBucket: 'edu-bridge-e58f4.appspot.com',
    measurementId: 'G-FY33Y8SFPK',
  );
}
